version = 1
SPDX-PackageName = "ghsecretman"
SPDX-PackageSupplier = "Weston Schmidt <weston_schmidt@alumni.purdue.edu>"
SPDX-PackageDownloadLocation = "https://github.com/schmidtw/ghsecretman"

[[annotations]]
path = [ "go.mod", "go.sum" ]
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2026 Weston Schmidt <weston_schmidt@alumni.purdue.edu>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2026 Weston Schmidt <weston_schmidt@alumni.purdue.edu>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2026 Weston Schmidt <weston_schmidt@alumni.purdue.edu>"
SPDX-License-Identifier = "Apache-2.0"