# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@b275f4ac4e5a4df525e54f88119c542099f1c2ee # v6.1.0
    secrets: inherit
