# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@33c6a137ac84da9ac12adb2ca7c3f4dc78d6666c # v6.1.0
    secrets: inherit
