# SPDX-FileCopyrightText: 2022 Weston Schmidt <weston_schmidt@alumni.purdue.edu>
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  ci:
    uses: goschtalt/.github/.github/workflows/approve-dependabot.yml@931de9fb4fe70bb6a017c2e28bfcfbd8b8cc3038 # v6.1.0
    secrets: inherit
